_target_: src.datamodules.nuscenes_datamodule.NuScenesDataModule

# This config file is used for running the template default tests

datasets:
  dataroot: "/data/karthik/bev_perception/data"  # Ensure `paths.dataroot` is set in a global config
  version: "v1.0-mini"
  nsweeps: 1
  centroid: [0.0, 2.0, 0.0]
  bounds: [-50.0, 50.0, -5.0, 5.0, -50.0, 50.0]
  res_3d: [200, 8, 200]
  seqlen: 1
  refcam_id: 1
  get_tids: False
  temporal_aug: False
  use_radar_filters: False
  do_shuffle_cams: True
  seed: 42
  data_aug_conf: 
        crop_offset: 89.6
        resize_lim: [0.8,1.2]
        final_dim: [448,832]
        H: 900
        W: 1600
        cams: ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT',
                 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT']
        ncams: 6

transforms:
  train:
    order: ["normalize"]
    normalize:
      _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]  # ImageNet mean for RGB images
      std: [0.229, 0.224, 0.225]   # ImageNet std for RGB images
      p: 1.0

  valid_test_predict:
    order: ["normalize"]
    normalize:
      _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      p: 1.0

loaders:
  train:
    batch_size: 32
    shuffle: True
    num_workers: 32
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 32
    shuffle: False
    num_workers: 32
    drop_last: False
    pin_memory: False